"""Theme content builder - Generates GRUB theme.txt content from configuration.

This module follows Single Responsibility Principle by focusing solely on
building the theme.txt content string from a ThemeConfiguration object.
"""

from dataclasses import dataclass

from src.core.config.theme_config import ThemeConfiguration
from src.utils.config import ALLOWED_GRUB_COLOR_NAMES, GRUB_COLOR_TO_HEX
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class ThemeColors:
    """Validated and converted theme colors (immutable)."""

    normal_fg: str
    normal_bg: str
    highlight_fg: str
    background_color: str
    label_color: str
    progress_fg: str
    progress_bg: str
    progress_border: str


class ThemeContentBuilder:
    """Builds GRUB theme.txt content following official GRUB2 gfxmenu specification.

    Single Responsibility: Only builds theme content string.
    """

    @staticmethod
    def _validate_color(color: str) -> str:
        """Validate and convert a color to hex format.

        Args:
            color: Color name or hex value

        Returns:
            Validated hex color

        """
        color = color.strip()

        # If it's already hex, validate format
        if color.startswith("#"):
            if len(color) == 7 and all(c in "0123456789ABCDEFabcdef" for c in color[1:]):
                return color.lower()
            logger.warning("Invalid hex color '%s', using white", color)
            return "#ffffff"

        # Convert color name to hex
        color_lower = color.lower()
        if color_lower in ALLOWED_GRUB_COLOR_NAMES:
            return GRUB_COLOR_TO_HEX[color_lower]

        logger.warning("Invalid color name '%s', using white", color)
        return "#ffffff"

    @classmethod
    def _prepare_colors(cls, config: ThemeConfiguration) -> ThemeColors:
        """Prepare and validate all colors from configuration.

        Args:
            config: Theme configuration

        Returns:
            ThemeColors object with validated hex colors

        """
        return ThemeColors(
            normal_fg=cls._validate_color(config.normal_fg),
            normal_bg=cls._validate_color(config.normal_bg),
            highlight_fg=cls._validate_color(config.highlight_fg),
            background_color=cls._validate_color(config.desktop_color),
            label_color=cls._validate_color(config.label_color),
            progress_fg=cls._validate_color(config.progress_fg),
            progress_bg=cls._validate_color(config.progress_bg),
            progress_border=cls._validate_color(config.progress_border),
        )

    @staticmethod
    def _build_header(background_path: str, background_color: str) -> str:
        """Build theme header section.

        Args:
            background_path: Path to background image
            background_color: Background color in hex

        Returns:
            Header content

        """
        lines = ["# GRUB2 gfxmenu theme generated by GRUB Manager", ""]

        if background_path and background_path.strip():
            lines.append(f'desktop-image: "{background_path}"')
        else:
            lines.append(f"desktop-color: {background_color}")

        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _build_title(config: ThemeConfiguration, label_color: str) -> str:
        """Build title section.

        Args:
            config: Theme configuration
            label_color: Label color in hex

        Returns:
            Title content

        """
        if not config.title_text or not config.title_text.strip():
            return ""

        font = f"{config.font_label} {config.font_label_size}"
        return (
            f"+ label {{\n"
            f'    text = "{config.title_text}"\n'
            f"    font = {font}\n"
            f"    color = {label_color}\n"
            f"    left = {config.label_left}\n"
            f"    top = {config.label_top}\n"
            f"}}\n\n"
        )

    @staticmethod
    def _build_boot_menu(config: ThemeConfiguration, colors: ThemeColors) -> str:
        """Build boot menu section.

        Args:
            config: Theme configuration
            colors: Validated theme colors

        Returns:
            Boot menu content

        """
        font_normal = f"{config.font_normal} {config.font_normal_size}"
        font_highlight = f"{config.font_highlight} {config.font_highlight_size}"

        return (
            f"+ boot_menu {{\n"
            f"    left = {config.menu_left}\n"
            f"    top = {config.menu_top}\n"
            f"    width = {config.menu_width}\n"
            f"    height = {config.menu_height}\n"
            f"    item_font = {font_normal}\n"
            f"    item_color = {colors.normal_fg}\n"
            f"    item_height = {config.item_height}\n"
            f"    item_padding = {config.item_padding}\n"
            f"    item_spacing = {config.item_spacing}\n"
            f"    selected_item_font = {font_highlight}\n"
            f"    selected_item_color = {colors.highlight_fg}\n"
            f'    selected_item_pixmap_style = "selected_*.png"\n'
            f"}}\n\n"
        )

    @staticmethod
    def _build_progress_bar(config: ThemeConfiguration, colors: ThemeColors) -> str:
        """Build progress bar section.

        Args:
            config: Theme configuration
            colors: Validated theme colors

        Returns:
            Progress bar content

        """
        return (
            f"+ progress_bar {{\n"
            f"    left = {config.progress_left}\n"
            f"    top = {config.progress_bottom}\n"
            f"    width = {config.progress_width}\n"
            f"    height = {config.progress_height}\n"
            f"    fg_color = {colors.progress_fg}\n"
            f"    bg_color = {colors.progress_bg}\n"
            f"    border_color = {colors.progress_border}\n"
            f"}}\n\n"
        )

    @staticmethod
    def _build_label(config: ThemeConfiguration, label_color: str) -> str:
        """Build label section.

        Args:
            config: Theme configuration
            label_color: Label color in hex

        Returns:
            Label content

        """
        if not config.label_text or not config.label_text.strip():
            return ""

        font = f"{config.font_label} {config.font_label_size}"
        return (
            f"+ label {{\n"
            f'    text = "{config.label_text}"\n'
            f"    font = {font}\n"
            f"    color = {label_color}\n"
            f"    left = {config.label_left}\n"
            f"    top = {config.label_top}\n"
            f"}}\n"
        )

    @classmethod
    def build(cls, config: ThemeConfiguration) -> str:
        """Build complete theme.txt content from configuration.

        Args:
            config: Theme configuration

        Returns:
            Complete theme.txt content

        """
        colors = cls._prepare_colors(config)

        content_parts = [
            cls._build_header(config.background_image, colors.background_color),
            cls._build_title(config, colors.label_color),
            cls._build_boot_menu(config, colors),
            cls._build_progress_bar(config, colors),
            cls._build_label(config, colors.label_color),
        ]

        return "".join(content_parts)
